project:
  type: website

website:
  title: "Fouzia Farooq"
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - publications.qmd
      - teaching.qmd

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: visual

